<template><div class="capability-page"><div class="orb" aria-hidden="true"><span></span><el-icon><MagicStick /></el-icon></div><span class="eyebrow">FULL EDITION CAPABILITY</span><h1>{{ title }}</h1><p>{{ description }}</p><div class="features"><article v-for="feature in features" :key="feature.title"><el-icon><component :is="feature.icon" /></el-icon><div><strong>{{ feature.title }}</strong><span>{{ feature.description }}</span></div></article></div><div class="actions"><el-button size="large" @click="router.push('/aura/workspace')">返回工作台</el-button><el-button type="primary" size="large" @click="requireFullEdition(title, 'generate')">获取完整版</el-button></div></div></template>
<script setup lang="ts" name="AuraCapabilityPreview">
import { computed } from "vue";
import { useRoute, useRouter } from "vue-router";
import { useAuraPreviewGate } from "./preview/useAuraPreviewGate";
const route = useRoute(); const router = useRouter(); const { requireFullEdition } = useAuraPreviewGate();
const labels: Record<string, { title: string; description: string }> = { "ai-image": { title: "AI 生图", description: "支持文生图、图生图、风格控制与品牌视觉一致性管理。" }, "ai-video": { title: "AI 视频创作", description: "将品牌素材和创意脚本转化为适配多渠道的动态内容。" }, "ai-draw": { title: "AI 绘图", description: "在可编辑画布中完成扩图、重绘、局部修改与视觉排版。" }, tasks: { title: "任务中心", description: "统一查看模型任务、队列进度、失败重试和算力消耗。" } };
const config = computed(() => labels[String(route.params.capability)] || { title: "意境 AI 完整版能力", description: "连接创意配置、模型调用、资产管理和商用导出的完整工作流。" });
const title = computed(() => config.value.title); const description = computed(() => config.value.description);
const features = [{ title: "模型编排", description: "多模型选择、参数预设与稳定任务队列", icon: "Cpu" },{ title: "品牌一致性", description: "统一人物、产品、风格与品牌视觉口径", icon: "Stamp" },{ title: "团队资产", description: "云端素材、作品、模板和权限协作", icon: "Collection" },{ title: "商用导出", description: "高清原图、批量打包和多渠道适配", icon: "Download" }];
</script>
<style lang="scss" scoped>
.capability-page { display: flex; min-height: 100%; align-items: center; justify-content: center; flex-direction: column; padding: 40px 20px; text-align: center; border: 1px solid var(--ai-border); border-radius: 22px; background: radial-gradient(circle at 50% 0,rgba(139,92,246,.13),transparent 36%),#fff; box-shadow: var(--ai-shadow); }.orb { position: relative; display: grid; width: 100px; height: 100px; place-items: center; margin-bottom: 22px; border-radius: 28px; color: #fff; background: var(--ai-grad); box-shadow: 0 18px 48px rgba(109,40,217,.25); font-size: 38px; span { position: absolute; inset: -14px; border: 1px solid rgba(139,92,246,.18); border-radius: 36px; } }.eyebrow { color: var(--ai-violet-deep); font-size: 10px; font-weight: 700; letter-spacing: 1.6px; }.capability-page h1 { margin: 8px 0; font-size: clamp(25px,4vw,38px); }.capability-page > p { max-width: 620px; margin: 0; color: var(--ai-muted); font-size: 13px; line-height: 1.8; }.features { display: grid; width: min(780px,100%); grid-template-columns: repeat(4,1fr); gap: 12px; margin: 30px 0; article { display: flex; align-items: flex-start; gap: 8px; padding: 15px; border: 1px solid var(--ai-border); border-radius: 13px; text-align: left; background: #fff; .el-icon { flex-shrink: 0; margin-top: 2px; color: var(--ai-violet-deep); } div { display: flex; flex-direction: column; gap: 4px; } strong { font-size: 11px; } span { color: var(--ai-muted); font-size: 9px; line-height: 1.5; } } }.actions { display: flex; gap: 10px; }
@media (max-width: 720px) { .features { grid-template-columns: repeat(2,1fr); } } @media (max-width: 430px) { .features { grid-template-columns: 1fr; }.actions { width:100%; flex-direction:column; :deep(.el-button) { width:100%; margin:0; } } }
</style>
