import type { DemoMedia } from "../demoData";

/** 一次性正式目录快照：仅保留公开展示字段，ID 已重映射，运行时不访问正式环境。 */
export const mediaSnapshot: DemoMedia[] = [
  {
    "id": "snapshot-news-01",
    "provider_media_id": "snapshot-news-01",
    "type": "news",
    "name": "列举网(可指定地区)",
    "price0": 4,
    "price02": 0,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 2,
    "mbr": 2,
    "release_rate": 5,
    "area": "全国",
    "channel": "综合资讯",
    "collection_type": "不包百度网页收录",
    "portal_type": "以上都不是",
    "property": "可发GEO",
    "n_link": true,
    "contact_show": true,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-news-02",
    "provider_media_id": "snapshot-news-02",
    "type": "news",
    "name": "北京列举网",
    "price0": 4,
    "price02": 0,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 2,
    "mbr": 2,
    "release_rate": 10,
    "area": "全国",
    "channel": "综合资讯",
    "collection_type": "不包百度网页收录",
    "portal_type": "以上都不是",
    "property": "可发GEO",
    "n_link": true,
    "contact_show": true,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-news-03",
    "provider_media_id": "snapshot-news-03",
    "type": "news",
    "name": "中国新闻资讯网",
    "price0": 4,
    "price02": 0,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 631,
    "area": "全国",
    "channel": "综合资讯",
    "collection_type": "不包百度网页收录",
    "portal_type": "以上都不是",
    "property": "国庆可发",
    "n_link": true,
    "contact_show": true,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-news-04",
    "provider_media_id": "snapshot-news-04",
    "type": "news",
    "name": "中商网",
    "price0": 4,
    "price02": 0,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 206,
    "area": "全国",
    "channel": "商业资讯",
    "collection_type": "不包百度网页收录",
    "portal_type": "以上都不是",
    "property": "国庆可发",
    "n_link": true,
    "contact_show": true,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-news-05",
    "provider_media_id": "snapshot-news-05",
    "type": "news",
    "name": "健康网资讯",
    "price0": 4,
    "price02": 0,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 498,
    "area": "全国",
    "channel": "医疗健康",
    "collection_type": "不包百度网页收录",
    "portal_type": "以上都不是",
    "property": "11,国庆可发",
    "n_link": true,
    "contact_show": true,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-news-06",
    "provider_media_id": "snapshot-news-06",
    "type": "news",
    "name": "测试媒体",
    "price0": 4,
    "price02": 0,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 4,
    "mbr": 5,
    "release_rate": 3942,
    "area": "全国",
    "channel": "综合资讯",
    "collection_type": "不包百度网页收录",
    "portal_type": "以上都不是",
    "property": "晚上可发,25,可发GEO",
    "n_link": true,
    "contact_show": true,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-news-07",
    "provider_media_id": "snapshot-news-07",
    "type": "news",
    "name": "华南新闻网",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 0,
    "area": "全国",
    "channel": "综合资讯",
    "collection_type": "不包百度网页收录",
    "portal_type": "海外媒体",
    "property": "可发GEO",
    "n_link": true,
    "contact_show": true,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-news-08",
    "provider_media_id": "snapshot-news-08",
    "type": "news",
    "name": "搜了网",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 6,
    "mbr": 0,
    "release_rate": 0,
    "area": "全国",
    "channel": "综合资讯",
    "collection_type": "不包百度网页收录",
    "portal_type": "以上都不是",
    "property": "可发GEO",
    "n_link": true,
    "contact_show": true,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-news-09",
    "provider_media_id": "snapshot-news-09",
    "type": "news",
    "name": "蓝色河畔",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 21,
    "area": "全国",
    "channel": "综合资讯",
    "collection_type": "不包百度网页收录",
    "portal_type": "以上都不是",
    "property": "可发GEO",
    "n_link": true,
    "contact_show": true,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-news-10",
    "provider_media_id": "snapshot-news-10",
    "type": "news",
    "name": "新华北网",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 256,
    "area": "全国",
    "channel": "综合资讯",
    "collection_type": "不包百度网页收录",
    "portal_type": "以上都不是",
    "n_link": true,
    "contact_show": true,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-news-11",
    "provider_media_id": "snapshot-news-11",
    "type": "news",
    "name": "国际新能源报",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 360,
    "area": "全国",
    "channel": "综合资讯",
    "collection_type": "不包百度网页收录",
    "portal_type": "以上都不是",
    "property": "可发视频,晚上可发,25",
    "n_link": true,
    "contact_show": true,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-news-12",
    "provider_media_id": "snapshot-news-12",
    "type": "news",
    "name": "中国商业网",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 15,
    "area": "全国",
    "channel": "商业资讯",
    "collection_type": "不包百度网页收录",
    "portal_type": "以上都不是",
    "property": "可发视频,国庆可发",
    "n_link": true,
    "contact_show": true,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-news-13",
    "provider_media_id": "snapshot-news-13",
    "type": "news",
    "name": "环球新闻网",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 188,
    "area": "全国",
    "channel": "综合资讯",
    "collection_type": "不包百度网页收录",
    "portal_type": "以上都不是",
    "property": "晚上可发,25,可发GEO",
    "n_link": true,
    "contact_show": true,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-news-14",
    "provider_media_id": "snapshot-news-14",
    "type": "news",
    "name": "中国快讯网",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 512,
    "area": "全国",
    "channel": "综合资讯",
    "collection_type": "不包百度网页收录",
    "portal_type": "以上都不是",
    "n_link": true,
    "contact_show": true,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-news-15",
    "provider_media_id": "snapshot-news-15",
    "type": "news",
    "name": "华夏游戏网",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 599,
    "area": "全国",
    "channel": "游戏动漫",
    "collection_type": "不包百度网页收录",
    "portal_type": "以上都不是",
    "n_link": true,
    "contact_show": true,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-news-16",
    "provider_media_id": "snapshot-news-16",
    "type": "news",
    "name": "中捷经济周刊",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 44,
    "area": "全国",
    "channel": "财经金融",
    "collection_type": "不包百度网页收录",
    "portal_type": "以上都不是",
    "property": "国庆可发",
    "n_link": true,
    "contact_show": true,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-news-17",
    "provider_media_id": "snapshot-news-17",
    "type": "news",
    "name": "商圈",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 633,
    "area": "贵州",
    "channel": "商业资讯",
    "collection_type": "不包百度网页收录",
    "portal_type": "以上都不是",
    "n_link": true,
    "contact_show": true,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-news-18",
    "provider_media_id": "snapshot-news-18",
    "type": "news",
    "name": "南都时讯",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 418,
    "area": "贵州",
    "channel": "综合资讯",
    "collection_type": "不包百度网页收录",
    "portal_type": "以上都不是",
    "n_link": true,
    "contact_show": true,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-news-19",
    "provider_media_id": "snapshot-news-19",
    "type": "news",
    "name": "贵商网",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 208,
    "area": "贵州",
    "channel": "商业资讯",
    "collection_type": "不包百度网页收录",
    "portal_type": "以上都不是",
    "n_link": true,
    "contact_show": true,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-news-20",
    "provider_media_id": "snapshot-news-20",
    "type": "news",
    "name": "东方时讯",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 387,
    "area": "浙江",
    "channel": "综合资讯",
    "collection_type": "不包百度网页收录",
    "portal_type": "以上都不是",
    "property": "阅读量媒体",
    "n_link": true,
    "contact_show": true,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-news-21",
    "provider_media_id": "snapshot-news-21",
    "type": "news",
    "name": "浙商在线",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 376,
    "area": "浙江",
    "channel": "商业资讯",
    "collection_type": "不包百度网页收录",
    "portal_type": "以上都不是",
    "n_link": true,
    "contact_show": true,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-news-22",
    "provider_media_id": "snapshot-news-22",
    "type": "news",
    "name": "商业简讯",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 420,
    "area": "全国",
    "channel": "商业资讯",
    "collection_type": "不包百度网页收录",
    "portal_type": "以上都不是",
    "n_link": true,
    "contact_show": true,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-news-23",
    "provider_media_id": "snapshot-news-23",
    "type": "news",
    "name": "和同财讯",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 172,
    "area": "全国",
    "channel": "财经金融",
    "collection_type": "不包百度网页收录",
    "portal_type": "以上都不是",
    "n_link": true,
    "contact_show": true,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-news-24",
    "provider_media_id": "snapshot-news-24",
    "type": "news",
    "name": "新财网",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 475,
    "area": "全国",
    "channel": "综合资讯,商业资讯",
    "collection_type": "不包百度网页收录",
    "portal_type": "以上都不是",
    "n_link": true,
    "contact_show": true,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-news-25",
    "provider_media_id": "snapshot-news-25",
    "type": "news",
    "name": "京华在线",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 222,
    "area": "全国",
    "channel": "综合资讯",
    "collection_type": "不包百度网页收录",
    "portal_type": "以上都不是",
    "n_link": true,
    "contact_show": true,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-news-26",
    "provider_media_id": "snapshot-news-26",
    "type": "news",
    "name": "燕商网",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 235,
    "area": "全国",
    "channel": "商业资讯",
    "collection_type": "不包百度网页收录",
    "portal_type": "以上都不是",
    "n_link": true,
    "contact_show": true,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-news-27",
    "provider_media_id": "snapshot-news-27",
    "type": "news",
    "name": "四方财经",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 261,
    "area": "全国",
    "channel": "财经金融",
    "collection_type": "不包百度网页收录",
    "portal_type": "以上都不是",
    "n_link": true,
    "contact_show": true,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-news-28",
    "provider_media_id": "snapshot-news-28",
    "type": "news",
    "name": "21世纪网",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 535,
    "area": "全国",
    "channel": "综合资讯",
    "collection_type": "不包百度网页收录",
    "portal_type": "以上都不是",
    "n_link": true,
    "contact_show": true,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-news-29",
    "provider_media_id": "snapshot-news-29",
    "type": "news",
    "name": "深度财经",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 242,
    "area": "全国",
    "channel": "财经金融",
    "collection_type": "不包百度网页收录",
    "portal_type": "以上都不是",
    "n_link": true,
    "contact_show": true,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-news-30",
    "provider_media_id": "snapshot-news-30",
    "type": "news",
    "name": "科技之家",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 520,
    "area": "全国",
    "channel": "IT科技",
    "collection_type": "不包百度网页收录",
    "portal_type": "以上都不是",
    "n_link": true,
    "contact_show": true,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-self-01",
    "provider_media_id": "snapshot-self-01",
    "type": "self",
    "name": "实辉时尚",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 104,
    "reading": 1000,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 0,
    "channel": "今日头条",
    "industry_type": "时尚",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-self-02",
    "provider_media_id": "snapshot-self-02",
    "type": "self",
    "name": "京欧时尚",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 155,
    "reading": 1000,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 0,
    "channel": "今日头条",
    "industry_type": "时尚",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-self-03",
    "provider_media_id": "snapshot-self-03",
    "type": "self",
    "name": "飞界时尚",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 274,
    "reading": 1000,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 0,
    "channel": "今日头条",
    "industry_type": "时尚",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-self-04",
    "provider_media_id": "snapshot-self-04",
    "type": "self",
    "name": "诺来汽车说",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 106,
    "reading": 1000,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 0,
    "channel": "今日头条",
    "industry_type": "汽车",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-self-05",
    "provider_media_id": "snapshot-self-05",
    "type": "self",
    "name": "淡定船财经",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 252,
    "reading": 1000,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 0,
    "channel": "今日头条",
    "industry_type": "财经",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-self-06",
    "provider_media_id": "snapshot-self-06",
    "type": "self",
    "name": "硅之谷科技",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 322,
    "reading": 1000,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 0,
    "channel": "今日头条",
    "industry_type": "科技",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-self-07",
    "provider_media_id": "snapshot-self-07",
    "type": "self",
    "name": "复亿文化",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 560,
    "reading": 1000,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 0,
    "channel": "今日头条",
    "industry_type": "文化摄影",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-self-08",
    "provider_media_id": "snapshot-self-08",
    "type": "self",
    "name": "尔超文化",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 123,
    "reading": 1000,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 0,
    "channel": "今日头条",
    "industry_type": "文化摄影",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-self-09",
    "provider_media_id": "snapshot-self-09",
    "type": "self",
    "name": "映强科技",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 112,
    "reading": 1000,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 0,
    "channel": "今日头条",
    "industry_type": "科技",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-self-10",
    "provider_media_id": "snapshot-self-10",
    "type": "self",
    "name": "富豪科技",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 118,
    "reading": 1000,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 0,
    "channel": "今日头条",
    "industry_type": "科技",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-self-11",
    "provider_media_id": "snapshot-self-11",
    "type": "self",
    "name": "德聚富贵",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 384,
    "reading": 1000,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 0,
    "channel": "今日头条",
    "industry_type": "综合",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-self-12",
    "provider_media_id": "snapshot-self-12",
    "type": "self",
    "name": "智慧脑经济",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 268,
    "reading": 1000,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 0,
    "channel": "今日头条",
    "industry_type": "财经",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-self-13",
    "provider_media_id": "snapshot-self-13",
    "type": "self",
    "name": "洁迈经济",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 572,
    "reading": 1000,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 0,
    "channel": "今日头条",
    "industry_type": "财经",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-self-14",
    "provider_media_id": "snapshot-self-14",
    "type": "self",
    "name": "悦翔教育",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 202,
    "reading": 1000,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 0,
    "channel": "今日头条",
    "industry_type": "教育",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-self-15",
    "provider_media_id": "snapshot-self-15",
    "type": "self",
    "name": "网码科技",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 289,
    "reading": 1000,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 0,
    "channel": "今日头条",
    "industry_type": "科技",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-self-16",
    "provider_media_id": "snapshot-self-16",
    "type": "self",
    "name": "晖扬科技",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 124,
    "reading": 1000,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 0,
    "channel": "今日头条",
    "industry_type": "科技",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-self-17",
    "provider_media_id": "snapshot-self-17",
    "type": "self",
    "name": "汇玛数码",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 134,
    "reading": 1000,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 0,
    "channel": "今日头条",
    "industry_type": "科技",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-self-18",
    "provider_media_id": "snapshot-self-18",
    "type": "self",
    "name": "惠悦数码",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 105,
    "reading": 1000,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 0,
    "channel": "今日头条",
    "industry_type": "科技",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-self-19",
    "provider_media_id": "snapshot-self-19",
    "type": "self",
    "name": "凡新数码",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 391,
    "reading": 1000,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 0,
    "channel": "今日头条",
    "industry_type": "科技",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-self-20",
    "provider_media_id": "snapshot-self-20",
    "type": "self",
    "name": "湖语数码",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 314,
    "reading": 1000,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 0,
    "channel": "今日头条",
    "industry_type": "科技",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-self-21",
    "provider_media_id": "snapshot-self-21",
    "type": "self",
    "name": "力盈智能",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 291,
    "reading": 1000,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 0,
    "channel": "今日头条",
    "industry_type": "游戏",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-self-22",
    "provider_media_id": "snapshot-self-22",
    "type": "self",
    "name": "旋超智能",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 103,
    "reading": 1000,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 0,
    "channel": "今日头条",
    "industry_type": "游戏",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-self-23",
    "provider_media_id": "snapshot-self-23",
    "type": "self",
    "name": "名亿智能",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 135,
    "reading": 1000,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 0,
    "channel": "今日头条",
    "industry_type": "游戏",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-self-24",
    "provider_media_id": "snapshot-self-24",
    "type": "self",
    "name": "翔维智能",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 232,
    "reading": 1000,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 0,
    "channel": "今日头条",
    "industry_type": "游戏",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-self-25",
    "provider_media_id": "snapshot-self-25",
    "type": "self",
    "name": "电凯体育",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 124,
    "reading": 1000,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 0,
    "channel": "今日头条",
    "industry_type": "文化摄影",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-self-26",
    "provider_media_id": "snapshot-self-26",
    "type": "self",
    "name": "讯图财经",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 226,
    "reading": 1000,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 0,
    "channel": "今日头条",
    "industry_type": "财经",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-self-27",
    "provider_media_id": "snapshot-self-27",
    "type": "self",
    "name": "芳华依旧",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 381,
    "reading": 1000,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 0,
    "channel": "今日头条",
    "industry_type": "综合",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-self-28",
    "provider_media_id": "snapshot-self-28",
    "type": "self",
    "name": "讯原的汽车",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 128,
    "reading": 1000,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 0,
    "channel": "今日头条",
    "industry_type": "汽车",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-self-29",
    "provider_media_id": "snapshot-self-29",
    "type": "self",
    "name": "光英教育",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 311,
    "reading": 1000,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 0,
    "channel": "今日头条",
    "industry_type": "教育",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-self-30",
    "provider_media_id": "snapshot-self-30",
    "type": "self",
    "name": "宇瑞教育",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 132,
    "reading": 1000,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 0,
    "channel": "今日头条",
    "industry_type": "教育",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-wechat-01",
    "provider_media_id": "snapshot-wechat-01",
    "type": "wechat",
    "name": "生活科技记事",
    "price0": 9,
    "price02": 8,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 49,
    "area": "河北",
    "industry_type": "综合",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-wechat-02",
    "provider_media_id": "snapshot-wechat-02",
    "type": "wechat",
    "name": "最新信息快车",
    "price0": 9,
    "price02": 8,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 63,
    "area": "河北",
    "industry_type": "综合",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-wechat-03",
    "provider_media_id": "snapshot-wechat-03",
    "type": "wechat",
    "name": "科技生活有态度",
    "price0": 9,
    "price02": 8,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 77,
    "area": "河北",
    "industry_type": "科技",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-wechat-04",
    "provider_media_id": "snapshot-wechat-04",
    "type": "wechat",
    "name": "大千新观察",
    "price0": 11,
    "price02": 11,
    "price03": 0,
    "fans": 5220,
    "reading": 5410,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 118,
    "area": "全国",
    "industry_type": "综合",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-wechat-05",
    "provider_media_id": "snapshot-wechat-05",
    "type": "wechat",
    "name": "博文天下事",
    "price0": 11,
    "price02": 11,
    "price03": 0,
    "fans": 6050,
    "reading": 5400,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 32,
    "area": "全国",
    "industry_type": "综合",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-wechat-06",
    "provider_media_id": "snapshot-wechat-06",
    "type": "wechat",
    "name": "大千生活梦",
    "price0": 11,
    "price02": 11,
    "price03": 0,
    "fans": 5000,
    "reading": 5000,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 37,
    "area": "河北",
    "industry_type": "综合",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-wechat-07",
    "provider_media_id": "snapshot-wechat-07",
    "type": "wechat",
    "name": "科技帮生活",
    "price0": 11,
    "price02": 11,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 896,
    "area": "全国",
    "industry_type": "科技",
    "n_link": false,
    "contact_show": true,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-wechat-08",
    "provider_media_id": "snapshot-wechat-08",
    "type": "wechat",
    "name": "科技时网",
    "price0": 11,
    "price02": 11,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 911,
    "area": "全国",
    "industry_type": "科技",
    "n_link": false,
    "contact_show": true,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-wechat-09",
    "provider_media_id": "snapshot-wechat-09",
    "type": "wechat",
    "name": "溯光计算科技",
    "price0": 11,
    "price02": 11,
    "price03": 0,
    "fans": 100,
    "reading": 100,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 611,
    "area": "全国",
    "industry_type": "科技",
    "n_link": true,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-wechat-10",
    "provider_media_id": "snapshot-wechat-10",
    "type": "wechat",
    "name": "科技时代瑟尔图",
    "price0": 11,
    "price02": 11,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 2025,
    "area": "湖北",
    "industry_type": "科技",
    "n_link": true,
    "contact_show": true,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-wechat-11",
    "provider_media_id": "snapshot-wechat-11",
    "type": "wechat",
    "name": "聆思智能系统",
    "price0": 11,
    "price02": 11,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 0,
    "area": "湖北",
    "industry_type": "科技",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-wechat-12",
    "provider_media_id": "snapshot-wechat-12",
    "type": "wechat",
    "name": "城事新印记",
    "price0": 11,
    "price02": 9,
    "price03": 0,
    "fans": 128,
    "reading": 666,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 65,
    "area": "全国",
    "industry_type": "综合",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-wechat-13",
    "provider_media_id": "snapshot-wechat-13",
    "type": "wechat",
    "name": "大千生活有态度",
    "price0": 11,
    "price02": 11,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 81,
    "area": "全国",
    "industry_type": "综合",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-wechat-14",
    "provider_media_id": "snapshot-wechat-14",
    "type": "wechat",
    "name": "一路有方",
    "price0": 12,
    "price02": 8,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 1350,
    "area": "全国",
    "industry_type": "健康",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-wechat-15",
    "provider_media_id": "snapshot-wechat-15",
    "type": "wechat",
    "name": "现场云",
    "price0": 12,
    "price02": 11,
    "price03": 0,
    "fans": 16,
    "reading": 4,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 0,
    "area": "全国",
    "industry_type": "科技",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-wechat-16",
    "provider_media_id": "snapshot-wechat-16",
    "type": "wechat",
    "name": "现场云讯",
    "price0": 12,
    "price02": 11,
    "price03": 0,
    "fans": 3,
    "reading": 3,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 0,
    "area": "全国",
    "industry_type": "财经",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-wechat-17",
    "provider_media_id": "snapshot-wechat-17",
    "type": "wechat",
    "name": "商业汇览",
    "price0": 12,
    "price02": 12,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 182,
    "area": "全国",
    "industry_type": "财经",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-wechat-18",
    "provider_media_id": "snapshot-wechat-18",
    "type": "wechat",
    "name": "新视科技",
    "price0": 12,
    "price02": 12,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 119,
    "area": "全国",
    "industry_type": "科技",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-wechat-19",
    "provider_media_id": "snapshot-wechat-19",
    "type": "wechat",
    "name": "中讯生活",
    "price0": 12,
    "price02": 12,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 1121,
    "area": "全国",
    "industry_type": "生活消费",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-wechat-20",
    "provider_media_id": "snapshot-wechat-20",
    "type": "wechat",
    "name": "茂智科技",
    "price0": 12,
    "price02": 12,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 0,
    "area": "全国",
    "industry_type": "科技",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-wechat-21",
    "provider_media_id": "snapshot-wechat-21",
    "type": "wechat",
    "name": "科讯新视",
    "price0": 12,
    "price02": 12,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 315,
    "area": "全国",
    "industry_type": "科技",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-wechat-22",
    "provider_media_id": "snapshot-wechat-22",
    "type": "wechat",
    "name": "悦博科技",
    "price0": 12,
    "price02": 12,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 0,
    "area": "全国",
    "industry_type": "科技",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-wechat-23",
    "provider_media_id": "snapshot-wechat-23",
    "type": "wechat",
    "name": "云经科技",
    "price0": 12,
    "price02": 12,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 0,
    "area": "全国",
    "industry_type": "科技",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-wechat-24",
    "provider_media_id": "snapshot-wechat-24",
    "type": "wechat",
    "name": "半岛商论",
    "price0": 12,
    "price02": 12,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 212,
    "area": "全国",
    "industry_type": "财经",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-wechat-25",
    "provider_media_id": "snapshot-wechat-25",
    "type": "wechat",
    "name": "市场关察",
    "price0": 12,
    "price02": 12,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 1002,
    "area": "全国",
    "industry_type": "科技",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-wechat-26",
    "provider_media_id": "snapshot-wechat-26",
    "type": "wechat",
    "name": "生活科技新潮",
    "price0": 12,
    "price02": 12,
    "price03": 0,
    "fans": 5110,
    "reading": 4100,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 46,
    "area": "全国",
    "industry_type": "科技",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-wechat-27",
    "provider_media_id": "snapshot-wechat-27",
    "type": "wechat",
    "name": "科技生活新发现",
    "price0": 12,
    "price02": 12,
    "price03": 0,
    "fans": 4000,
    "reading": 4000,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 47,
    "area": "全国",
    "industry_type": "科技",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-wechat-28",
    "provider_media_id": "snapshot-wechat-28",
    "type": "wechat",
    "name": "生活科技见闻",
    "price0": 12,
    "price02": 12,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 72,
    "area": "河北",
    "industry_type": "科技",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-wechat-29",
    "provider_media_id": "snapshot-wechat-29",
    "type": "wechat",
    "name": "富玉科技网",
    "price0": 12,
    "price02": 0,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 804,
    "area": "全国",
    "industry_type": "科技",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-wechat-30",
    "provider_media_id": "snapshot-wechat-30",
    "type": "wechat",
    "name": "生活科技知行圈",
    "price0": 12,
    "price02": 12,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 96,
    "area": "全国",
    "industry_type": "综合",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-weibo-01",
    "provider_media_id": "snapshot-weibo-01",
    "type": "weibo",
    "name": "王h0",
    "price0": 3,
    "price02": 3,
    "price03": 3,
    "fans": 11000,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 565,
    "area": "全国",
    "industry_type": "综合",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-weibo-02",
    "provider_media_id": "snapshot-weibo-02",
    "type": "weibo",
    "name": "理想家居录",
    "price0": 3,
    "price02": 3,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 689,
    "area": "河北",
    "industry_type": "房产家居",
    "n_link": true,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-weibo-03",
    "provider_media_id": "snapshot-weibo-03",
    "type": "weibo",
    "name": "妈咪顾问团",
    "price0": 3,
    "price02": 3,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 409,
    "area": "河北",
    "industry_type": "母婴亲子",
    "n_link": true,
    "contact_show": true,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-weibo-04",
    "provider_media_id": "snapshot-weibo-04",
    "type": "weibo",
    "name": "科学育儿研究所",
    "price0": 3,
    "price02": 3,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 271,
    "area": "河北",
    "industry_type": "母婴亲子",
    "n_link": true,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-weibo-05",
    "provider_media_id": "snapshot-weibo-05",
    "type": "weibo",
    "name": "宝妈UP日记",
    "price0": 3,
    "price02": 3,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 500,
    "area": "河北",
    "industry_type": "母婴亲子",
    "n_link": true,
    "contact_show": true,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-weibo-06",
    "provider_media_id": "snapshot-weibo-06",
    "type": "weibo",
    "name": "萌娃语录bot",
    "price0": 3,
    "price02": 3,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 418,
    "area": "河北",
    "industry_type": "母婴亲子",
    "n_link": true,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-weibo-07",
    "provider_media_id": "snapshot-weibo-07",
    "type": "weibo",
    "name": "信息风暴眼",
    "price0": 3,
    "price02": 3,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 241,
    "area": "河北",
    "industry_type": "综合",
    "n_link": true,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-weibo-08",
    "provider_media_id": "snapshot-weibo-08",
    "type": "weibo",
    "name": "华晨观点",
    "price0": 5,
    "price02": 5,
    "price03": 5,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 69,
    "area": "全国",
    "industry_type": "社会",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-weibo-09",
    "provider_media_id": "snapshot-weibo-09",
    "type": "weibo",
    "name": "都市圈之音",
    "price0": 5,
    "price02": 5,
    "price03": 5,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 36,
    "area": "全国",
    "industry_type": "社会",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-weibo-10",
    "provider_media_id": "snapshot-weibo-10",
    "type": "weibo",
    "name": "中经视记",
    "price0": 5,
    "price02": 5,
    "price03": 5,
    "fans": 1048,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 0,
    "area": "全国",
    "industry_type": "综合",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-weibo-11",
    "provider_media_id": "snapshot-weibo-11",
    "type": "weibo",
    "name": "财商时代看点",
    "price0": 5,
    "price02": 5,
    "price03": 0,
    "fans": 600,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 89,
    "area": "河北",
    "industry_type": "商业",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-weibo-12",
    "provider_media_id": "snapshot-weibo-12",
    "type": "weibo",
    "name": "知微新印记（可发视频）",
    "price0": 5,
    "price02": 5,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 419,
    "area": "江西",
    "industry_type": "综合",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-weibo-13",
    "provider_media_id": "snapshot-weibo-13",
    "type": "weibo",
    "name": "十字讯号（可发视频）",
    "price0": 5,
    "price02": 5,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 211,
    "area": "江西",
    "industry_type": "综合",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-weibo-14",
    "provider_media_id": "snapshot-weibo-14",
    "type": "weibo",
    "name": "今日要义",
    "price0": 5,
    "price02": 5,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 373,
    "area": "江西",
    "industry_type": "综合",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-weibo-15",
    "provider_media_id": "snapshot-weibo-15",
    "type": "weibo",
    "name": "深度速递员",
    "price0": 5,
    "price02": 5,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 401,
    "area": "江西",
    "industry_type": "综合",
    "n_link": false,
    "contact_show": false,
    "gfrz": 1,
    "self_vrz": 0
  },
  {
    "id": "snapshot-weibo-16",
    "provider_media_id": "snapshot-weibo-16",
    "type": "weibo",
    "name": "前沿雷达",
    "price0": 5,
    "price02": 5,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 454,
    "area": "江西",
    "industry_type": "综合",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-weibo-17",
    "provider_media_id": "snapshot-weibo-17",
    "type": "weibo",
    "name": "深度24H（可发视频）",
    "price0": 5,
    "price02": 5,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 297,
    "area": "江西",
    "industry_type": "综合",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-weibo-18",
    "provider_media_id": "snapshot-weibo-18",
    "type": "weibo",
    "name": "产经洞察",
    "price0": 5,
    "price02": 5,
    "price03": 5,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 1592,
    "area": "全国",
    "industry_type": "综合",
    "n_link": true,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-weibo-19",
    "provider_media_id": "snapshot-weibo-19",
    "type": "weibo",
    "name": "每日实况",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 3306,
    "area": "全国",
    "industry_type": "综合",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-weibo-20",
    "provider_media_id": "snapshot-weibo-20",
    "type": "weibo",
    "name": "每日百闻",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 5401,
    "area": "全国",
    "industry_type": "综合",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-weibo-21",
    "provider_media_id": "snapshot-weibo-21",
    "type": "weibo",
    "name": "商界之秀",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 192,
    "area": "全国",
    "industry_type": "财经",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-weibo-22",
    "provider_media_id": "snapshot-weibo-22",
    "type": "weibo",
    "name": "商业速递",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 321,
    "area": "全国",
    "industry_type": "财经",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-weibo-23",
    "provider_media_id": "snapshot-weibo-23",
    "type": "weibo",
    "name": "极目财经",
    "price0": 5,
    "price02": 5,
    "price03": 5,
    "fans": 1,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 637,
    "area": "全国",
    "industry_type": "财经",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-weibo-24",
    "provider_media_id": "snapshot-weibo-24",
    "type": "weibo",
    "name": "丰亚-财经",
    "price0": 5,
    "price02": 5,
    "price03": 5,
    "fans": 4,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 208,
    "area": "全国",
    "industry_type": "财经",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-weibo-25",
    "provider_media_id": "snapshot-weibo-25",
    "type": "weibo",
    "name": "今日财经说谈",
    "price0": 5,
    "price02": 5,
    "price03": 5,
    "fans": 1,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 399,
    "area": "全国",
    "industry_type": "财经",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-weibo-26",
    "provider_media_id": "snapshot-weibo-26",
    "type": "weibo",
    "name": "生活科技新观",
    "price0": 5,
    "price02": 5,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 668,
    "area": "全国",
    "industry_type": "综合",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-weibo-27",
    "provider_media_id": "snapshot-weibo-27",
    "type": "weibo",
    "name": "时代生活前沿",
    "price0": 5,
    "price02": 5,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 193,
    "area": "全国",
    "industry_type": "综合",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-weibo-28",
    "provider_media_id": "snapshot-weibo-28",
    "type": "weibo",
    "name": "科技智能汇",
    "price0": 5,
    "price02": 5,
    "price03": 5,
    "fans": 47000,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 185,
    "area": "全国",
    "industry_type": "科技",
    "n_link": true,
    "contact_show": true,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-weibo-29",
    "provider_media_id": "snapshot-weibo-29",
    "type": "weibo",
    "name": "每日财经谈",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 2225,
    "area": "全国",
    "channel": "主持人",
    "industry_type": "财经",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-weibo-30",
    "provider_media_id": "snapshot-weibo-30",
    "type": "weibo",
    "name": "朝文早知",
    "price0": 5,
    "price02": 0,
    "price03": 0,
    "fans": 0,
    "reading": 0,
    "pcbr": 0,
    "mbr": 0,
    "release_rate": 3419,
    "area": "全国",
    "channel": "影视演员",
    "industry_type": "综合",
    "n_link": false,
    "contact_show": false,
    "gfrz": 0,
    "self_vrz": 0
  },
  {
    "id": "snapshot-xiaohongshu-01",
    "provider_media_id": "snapshot-xiaohongshu-01",
    "type": "xiaohongshu",
    "account_name": "草莓布丁",
    "city": "浙江",
    "industry": "生活记录,综合",
    "followers_count": 13000,
    "note_art_avg_read": 500,
    "note_video_avg_read": 800,
    "note_art_price": 43,
    "note_video_price": 43
  },
  {
    "id": "snapshot-xiaohongshu-02",
    "provider_media_id": "snapshot-xiaohongshu-02",
    "type": "xiaohongshu",
    "account_name": "钱多多福多多",
    "city": "河南",
    "industry": "生活记录,综合",
    "followers_count": 10209,
    "note_art_avg_read": 500,
    "note_video_avg_read": 800,
    "note_art_price": 43,
    "note_video_price": 43
  },
  {
    "id": "snapshot-xiaohongshu-03",
    "provider_media_id": "snapshot-xiaohongshu-03",
    "type": "xiaohongshu",
    "account_name": "小喵喵",
    "city": "河南",
    "industry": "生活记录,综合",
    "followers_count": 10209,
    "note_art_avg_read": 500,
    "note_video_avg_read": 800,
    "note_art_price": 43,
    "note_video_price": 43
  },
  {
    "id": "snapshot-xiaohongshu-04",
    "provider_media_id": "snapshot-xiaohongshu-04",
    "type": "xiaohongshu",
    "account_name": "小樱桃??",
    "city": "广东",
    "industry": "生活记录,综合",
    "followers_count": 11000,
    "note_art_avg_read": 500,
    "note_video_avg_read": 800,
    "note_art_price": 43,
    "note_video_price": 43
  },
  {
    "id": "snapshot-xiaohongshu-05",
    "provider_media_id": "snapshot-xiaohongshu-05",
    "type": "xiaohongshu",
    "account_name": "呆呆甜熊??",
    "city": "广东",
    "industry": "生活记录,综合",
    "followers_count": 28000,
    "note_art_avg_read": 500,
    "note_video_avg_read": 800,
    "note_art_price": 43,
    "note_video_price": 43
  },
  {
    "id": "snapshot-xiaohongshu-06",
    "provider_media_id": "snapshot-xiaohongshu-06",
    "type": "xiaohongshu",
    "account_name": "夏雨",
    "city": "广东",
    "industry": "生活记录,综合",
    "followers_count": 30000,
    "note_art_avg_read": 500,
    "note_video_avg_read": 800,
    "note_art_price": 43,
    "note_video_price": 43
  },
  {
    "id": "snapshot-xiaohongshu-07",
    "provider_media_id": "snapshot-xiaohongshu-07",
    "type": "xiaohongshu",
    "account_name": "泡泡糖",
    "city": "广东",
    "industry": "生活记录,综合",
    "followers_count": 21000,
    "note_art_avg_read": 500,
    "note_video_avg_read": 800,
    "note_art_price": 43,
    "note_video_price": 43
  },
  {
    "id": "snapshot-xiaohongshu-08",
    "provider_media_id": "snapshot-xiaohongshu-08",
    "type": "xiaohongshu",
    "account_name": "小蘑菇",
    "city": "广东",
    "industry": "生活记录,综合",
    "followers_count": 18000,
    "note_art_avg_read": 500,
    "note_video_avg_read": 800,
    "note_art_price": 43,
    "note_video_price": 43
  },
  {
    "id": "snapshot-xiaohongshu-09",
    "provider_media_id": "snapshot-xiaohongshu-09",
    "type": "xiaohongshu",
    "account_name": "早安",
    "city": "河北",
    "industry": "生活记录,综合",
    "followers_count": 2200,
    "note_art_avg_read": 500,
    "note_video_avg_read": 800,
    "note_art_price": 23,
    "note_video_price": 23
  },
  {
    "id": "snapshot-xiaohongshu-10",
    "provider_media_id": "snapshot-xiaohongshu-10",
    "type": "xiaohongshu",
    "account_name": "萌萌的小宝",
    "city": "河北",
    "industry": "生活记录,综合",
    "followers_count": 1400,
    "note_art_avg_read": 500,
    "note_video_avg_read": 800,
    "note_art_price": 23,
    "note_video_price": 23
  },
  {
    "id": "snapshot-xiaohongshu-11",
    "provider_media_id": "snapshot-xiaohongshu-11",
    "type": "xiaohongshu",
    "account_name": "小开心开心",
    "city": "河北",
    "industry": "生活记录,综合",
    "followers_count": 1500,
    "note_art_avg_read": 500,
    "note_video_avg_read": 800,
    "note_art_price": 23,
    "note_video_price": 23
  },
  {
    "id": "snapshot-xiaohongshu-12",
    "provider_media_id": "snapshot-xiaohongshu-12",
    "type": "xiaohongshu",
    "account_name": "调羹白",
    "city": "河北",
    "industry": "生活记录,综合",
    "followers_count": 1700,
    "note_art_avg_read": 500,
    "note_video_avg_read": 800,
    "note_art_price": 23,
    "note_video_price": 23
  },
  {
    "id": "snapshot-xiaohongshu-13",
    "provider_media_id": "snapshot-xiaohongshu-13",
    "type": "xiaohongshu",
    "account_name": "金针菇",
    "city": "河南",
    "industry": "生活记录,综合",
    "followers_count": 10000,
    "note_art_avg_read": 500,
    "note_video_avg_read": 800,
    "note_art_price": 43,
    "note_video_price": 43
  },
  {
    "id": "snapshot-xiaohongshu-14",
    "provider_media_id": "snapshot-xiaohongshu-14",
    "type": "xiaohongshu",
    "account_name": "柠檬水",
    "city": "河南",
    "industry": "生活记录,综合",
    "followers_count": 10000,
    "note_art_avg_read": 500,
    "note_video_avg_read": 800,
    "note_art_price": 43,
    "note_video_price": 43
  },
  {
    "id": "snapshot-xiaohongshu-15",
    "provider_media_id": "snapshot-xiaohongshu-15",
    "type": "xiaohongshu",
    "account_name": "赴一场星河",
    "city": "河南",
    "industry": "生活记录,综合",
    "followers_count": 10000,
    "note_art_avg_read": 500,
    "note_video_avg_read": 800,
    "note_art_price": 43,
    "note_video_price": 43
  },
  {
    "id": "snapshot-xiaohongshu-16",
    "provider_media_id": "snapshot-xiaohongshu-16",
    "type": "xiaohongshu",
    "account_name": "卡布基诺",
    "city": "河南",
    "industry": "生活记录,综合",
    "followers_count": 10000,
    "note_art_avg_read": 500,
    "note_video_avg_read": 800,
    "note_art_price": 43,
    "note_video_price": 43
  },
  {
    "id": "snapshot-xiaohongshu-17",
    "provider_media_id": "snapshot-xiaohongshu-17",
    "type": "xiaohongshu",
    "account_name": "西瓜糖",
    "city": "河南",
    "industry": "生活记录,综合",
    "followers_count": 10000,
    "note_art_avg_read": 500,
    "note_video_avg_read": 800,
    "note_art_price": 43,
    "note_video_price": 43
  },
  {
    "id": "snapshot-xiaohongshu-18",
    "provider_media_id": "snapshot-xiaohongshu-18",
    "type": "xiaohongshu",
    "account_name": "风吹叶落",
    "city": "广东",
    "industry": "生活记录,综合",
    "followers_count": 10000,
    "note_art_avg_read": 500,
    "note_video_avg_read": 800,
    "note_art_price": 43,
    "note_video_price": 43
  },
  {
    "id": "snapshot-xiaohongshu-19",
    "provider_media_id": "snapshot-xiaohongshu-19",
    "type": "xiaohongshu",
    "account_name": "幸福",
    "city": "新疆",
    "industry": "生活记录",
    "followers_count": 10000,
    "note_art_avg_read": 500,
    "note_video_avg_read": 800,
    "note_art_price": 43,
    "note_video_price": 43
  },
  {
    "id": "snapshot-xiaohongshu-20",
    "provider_media_id": "snapshot-xiaohongshu-20",
    "type": "xiaohongshu",
    "account_name": "小铃铛",
    "city": "新疆",
    "industry": "生活记录",
    "followers_count": 15000,
    "note_art_avg_read": 500,
    "note_video_avg_read": 800,
    "note_art_price": 43,
    "note_video_price": 43
  },
  {
    "id": "snapshot-xiaohongshu-21",
    "provider_media_id": "snapshot-xiaohongshu-21",
    "type": "xiaohongshu",
    "account_name": "若曦",
    "city": "新疆",
    "industry": "生活记录",
    "followers_count": 21000,
    "note_art_avg_read": 500,
    "note_video_avg_read": 800,
    "note_art_price": 43,
    "note_video_price": 43
  },
  {
    "id": "snapshot-xiaohongshu-22",
    "provider_media_id": "snapshot-xiaohongshu-22",
    "type": "xiaohongshu",
    "account_name": "夏木",
    "city": "新疆",
    "industry": "生活记录",
    "followers_count": 18000,
    "note_art_avg_read": 500,
    "note_video_avg_read": 800,
    "note_art_price": 43,
    "note_video_price": 43
  },
  {
    "id": "snapshot-xiaohongshu-23",
    "provider_media_id": "snapshot-xiaohongshu-23",
    "type": "xiaohongshu",
    "account_name": "妈咪宝贝",
    "city": "新疆",
    "industry": "生活记录",
    "followers_count": 17000,
    "note_art_avg_read": 500,
    "note_video_avg_read": 800,
    "note_art_price": 43,
    "note_video_price": 43
  },
  {
    "id": "snapshot-xiaohongshu-24",
    "provider_media_id": "snapshot-xiaohongshu-24",
    "type": "xiaohongshu",
    "account_name": "兔兔姐",
    "city": "新疆",
    "industry": "生活记录",
    "followers_count": 13000,
    "note_art_avg_read": 500,
    "note_video_avg_read": 800,
    "note_art_price": 43,
    "note_video_price": 43
  },
  {
    "id": "snapshot-xiaohongshu-25",
    "provider_media_id": "snapshot-xiaohongshu-25",
    "type": "xiaohongshu",
    "account_name": "木子小欣",
    "city": "新疆",
    "industry": "生活记录",
    "followers_count": 11000,
    "note_art_avg_read": 500,
    "note_video_avg_read": 800,
    "note_art_price": 43,
    "note_video_price": 43
  },
  {
    "id": "snapshot-xiaohongshu-26",
    "provider_media_id": "snapshot-xiaohongshu-26",
    "type": "xiaohongshu",
    "account_name": "夏木妶清",
    "city": "新疆",
    "industry": "生活记录",
    "followers_count": 10000,
    "note_art_avg_read": 500,
    "note_video_avg_read": 800,
    "note_art_price": 43,
    "note_video_price": 43
  },
  {
    "id": "snapshot-xiaohongshu-27",
    "provider_media_id": "snapshot-xiaohongshu-27",
    "type": "xiaohongshu",
    "account_name": "乖乖",
    "city": "山西",
    "industry": "生活记录,综合",
    "followers_count": 11732,
    "note_art_avg_read": 500,
    "note_video_avg_read": 800,
    "note_art_price": 110,
    "note_video_price": 110
  },
  {
    "id": "snapshot-xiaohongshu-28",
    "provider_media_id": "snapshot-xiaohongshu-28",
    "type": "xiaohongshu",
    "account_name": "沐沐",
    "city": "山西",
    "industry": "生活记录,综合",
    "followers_count": 11673,
    "note_art_avg_read": 500,
    "note_video_avg_read": 800,
    "note_art_price": 43,
    "note_video_price": 43
  },
  {
    "id": "snapshot-xiaohongshu-29",
    "provider_media_id": "snapshot-xiaohongshu-29",
    "type": "xiaohongshu",
    "account_name": "爱玩手帐的琳琳",
    "city": "上海",
    "industry": "生活记录,综合",
    "followers_count": 12000,
    "note_art_avg_read": 500,
    "note_video_avg_read": 800,
    "note_art_price": 43,
    "note_video_price": 43
  },
  {
    "id": "snapshot-xiaohongshu-30",
    "provider_media_id": "snapshot-xiaohongshu-30",
    "type": "xiaohongshu",
    "account_name": "不将就",
    "city": "上海",
    "industry": "生活记录,综合",
    "followers_count": 20000,
    "note_art_avg_read": 500,
    "note_video_avg_read": 800,
    "note_art_price": 43,
    "note_video_price": 43
  },
  {
    "id": "snapshot-short-video-01",
    "provider_media_id": "snapshot-short-video-01",
    "type": "shortVideo",
    "account_name": "陈天没素质",
    "city": "福建",
    "province": "福建",
    "platform_name": "抖音",
    "industry": "萌宠",
    "audience_gender": "女",
    "fans": 1000,
    "price": 88
  },
  {
    "id": "snapshot-short-video-02",
    "provider_media_id": "snapshot-short-video-02",
    "type": "shortVideo",
    "account_name": "墩墩不是多多",
    "city": "四川",
    "province": "四川",
    "platform_name": "抖音",
    "industry": "萌宠",
    "audience_gender": "男",
    "fans": 13000,
    "price": 110
  },
  {
    "id": "snapshot-short-video-03",
    "provider_media_id": "snapshot-short-video-03",
    "type": "shortVideo",
    "account_name": "年糕日记",
    "city": "山东",
    "province": "山东",
    "platform_name": "抖音",
    "industry": "萌宠",
    "audience_gender": "女",
    "fans": 300,
    "price": 53
  },
  {
    "id": "snapshot-short-video-04",
    "provider_media_id": "snapshot-short-video-04",
    "type": "shortVideo",
    "account_name": "我真的不闹了",
    "city": "广西",
    "province": "广西",
    "platform_name": "抖音",
    "industry": "商业",
    "audience_gender": "女",
    "fans": 100,
    "price": 48
  },
  {
    "id": "snapshot-short-video-05",
    "provider_media_id": "snapshot-short-video-05",
    "type": "shortVideo",
    "account_name": "简阳建材供应商",
    "city": "四川",
    "province": "四川",
    "platform_name": "抖音",
    "industry": "商业",
    "audience_gender": "男",
    "fans": 4000,
    "price": 143
  },
  {
    "id": "snapshot-short-video-06",
    "provider_media_id": "snapshot-short-video-06",
    "type": "shortVideo",
    "account_name": "泡芙小柯基",
    "city": "辽宁",
    "province": "辽宁",
    "platform_name": "抖音",
    "industry": "萌宠",
    "audience_gender": "女",
    "fans": 2000,
    "price": 132
  },
  {
    "id": "snapshot-short-video-07",
    "provider_media_id": "snapshot-short-video-07",
    "type": "shortVideo",
    "account_name": "99健康网",
    "city": "全国",
    "province": "全国",
    "platform_name": "抖音",
    "industry": "健康医疗",
    "audience_gender": "不限",
    "fans": 0,
    "price": 23
  },
  {
    "id": "snapshot-short-video-08",
    "provider_media_id": "snapshot-short-video-08",
    "type": "shortVideo",
    "account_name": "铲屎官小李",
    "city": "湖北",
    "province": "湖北",
    "platform_name": "抖音",
    "industry": "萌宠",
    "audience_gender": "女",
    "fans": 3000,
    "price": 132
  },
  {
    "id": "snapshot-short-video-09",
    "provider_media_id": "snapshot-short-video-09",
    "type": "shortVideo",
    "account_name": "小多小帕是腊肠",
    "city": "湖北",
    "province": "湖北",
    "platform_name": "抖音",
    "industry": "萌宠",
    "audience_gender": "男",
    "fans": 4000,
    "price": 77
  },
  {
    "id": "snapshot-short-video-10",
    "provider_media_id": "snapshot-short-video-10",
    "type": "shortVideo",
    "account_name": "诚信河南",
    "city": "河南",
    "province": "河南",
    "platform_name": "快手",
    "industry": "综合",
    "audience_gender": "不限",
    "fans": 10000,
    "price": 77
  },
  {
    "id": "snapshot-short-video-11",
    "provider_media_id": "snapshot-short-video-11",
    "type": "shortVideo",
    "account_name": "诚信中原",
    "city": "河南",
    "province": "河南",
    "platform_name": "视频号",
    "industry": "综合",
    "audience_gender": "不限",
    "fans": 10000,
    "price": 77
  },
  {
    "id": "snapshot-short-video-12",
    "provider_media_id": "snapshot-short-video-12",
    "type": "shortVideo",
    "account_name": "搞活动",
    "city": "湖南",
    "province": "湖南",
    "platform_name": "抖音",
    "industry": "综合",
    "audience_gender": "不限",
    "fans": 9336,
    "price": 77
  },
  {
    "id": "snapshot-short-video-13",
    "provider_media_id": "snapshot-short-video-13",
    "type": "shortVideo",
    "account_name": "评酒网",
    "city": "湖南",
    "province": "湖南",
    "platform_name": "抖音",
    "industry": "生活",
    "audience_gender": "不限",
    "fans": 9336,
    "price": 143
  },
  {
    "id": "snapshot-short-video-14",
    "provider_media_id": "snapshot-short-video-14",
    "type": "shortVideo",
    "account_name": "小谭的好物",
    "city": "广西",
    "province": "广西",
    "platform_name": "视频号",
    "industry": "综合",
    "audience_gender": "不限",
    "fans": 13000,
    "price": 77
  },
  {
    "id": "snapshot-short-video-15",
    "provider_media_id": "snapshot-short-video-15",
    "type": "shortVideo",
    "account_name": "王球球",
    "city": "江苏",
    "province": "江苏",
    "platform_name": "抖音",
    "industry": "萌宠",
    "audience_gender": "不限",
    "fans": 405,
    "price": 43
  },
  {
    "id": "snapshot-short-video-16",
    "provider_media_id": "snapshot-short-video-16",
    "type": "shortVideo",
    "account_name": "半盏闲谈",
    "city": "湖北",
    "province": "湖北",
    "platform_name": "抖音",
    "industry": "综合",
    "audience_gender": "女",
    "fans": 0,
    "price": 209
  },
  {
    "id": "snapshot-short-video-17",
    "provider_media_id": "snapshot-short-video-17",
    "type": "shortVideo",
    "account_name": "88631",
    "city": "河南",
    "province": "河南",
    "platform_name": "抖音",
    "industry": "综合",
    "audience_gender": "不限",
    "fans": 29,
    "price": 13
  },
  {
    "id": "snapshot-short-video-18",
    "provider_media_id": "snapshot-short-video-18",
    "type": "shortVideo",
    "account_name": "生活碎碎念",
    "city": "全国",
    "province": "全国",
    "platform_name": "抖音",
    "industry": "生活",
    "audience_gender": "男",
    "fans": 68,
    "price": 110
  },
  {
    "id": "snapshot-short-video-19",
    "provider_media_id": "snapshot-short-video-19",
    "type": "shortVideo",
    "account_name": "晚桉的茶",
    "city": "安徽",
    "province": "安徽",
    "platform_name": "抖音",
    "industry": "美食",
    "audience_gender": "男",
    "fans": 785,
    "price": 264
  },
  {
    "id": "snapshot-short-video-20",
    "provider_media_id": "snapshot-short-video-20",
    "type": "shortVideo",
    "account_name": "小杨说剧",
    "city": "湖北",
    "province": "湖北",
    "platform_name": "抖音",
    "industry": "影视娱乐",
    "audience_gender": "不限",
    "fans": 1257,
    "price": 53
  },
  {
    "id": "snapshot-short-video-21",
    "provider_media_id": "snapshot-short-video-21",
    "type": "shortVideo",
    "account_name": "商事最前沿",
    "city": "全国",
    "province": "全国",
    "platform_name": "搜狐视频",
    "industry": "综合",
    "audience_gender": "不限",
    "fans": 100,
    "price": 11
  },
  {
    "id": "snapshot-short-video-22",
    "provider_media_id": "snapshot-short-video-22",
    "type": "shortVideo",
    "account_name": "科技知晓",
    "city": "全国",
    "province": "全国",
    "platform_name": "抖音",
    "industry": "科技数码",
    "audience_gender": "不限",
    "fans": 58000,
    "price": 105
  },
  {
    "id": "snapshot-short-video-23",
    "provider_media_id": "snapshot-short-video-23",
    "type": "shortVideo",
    "account_name": "商业白皮书",
    "city": "全国",
    "province": "全国",
    "platform_name": "视频号",
    "industry": "综合",
    "audience_gender": "不限",
    "fans": 100,
    "price": 15
  },
  {
    "id": "snapshot-short-video-24",
    "provider_media_id": "snapshot-short-video-24",
    "type": "shortVideo",
    "account_name": "优酷(时事报)",
    "city": "全国",
    "province": "全国",
    "platform_name": "优酷",
    "industry": "时尚/健康医疗/商业",
    "audience_gender": "不限",
    "fans": 1000,
    "price": 12
  },
  {
    "id": "snapshot-short-video-25",
    "provider_media_id": "snapshot-short-video-25",
    "type": "shortVideo",
    "account_name": "汽车热门生活",
    "city": "全国",
    "province": "全国",
    "platform_name": "视频号",
    "industry": "汽车",
    "audience_gender": "不限",
    "fans": 23000,
    "price": 33
  },
  {
    "id": "snapshot-short-video-26",
    "provider_media_id": "snapshot-short-video-26",
    "type": "shortVideo",
    "account_name": "汽车集结社",
    "city": "全国",
    "province": "全国",
    "platform_name": "视频号",
    "industry": "汽车",
    "audience_gender": "不限",
    "fans": 21400,
    "price": 33
  },
  {
    "id": "snapshot-short-video-27",
    "provider_media_id": "snapshot-short-video-27",
    "type": "shortVideo",
    "account_name": "汽车玩家阿诺",
    "city": "全国",
    "province": "全国",
    "platform_name": "视频号",
    "industry": "汽车",
    "audience_gender": "不限",
    "fans": 20000,
    "price": 48
  },
  {
    "id": "snapshot-short-video-28",
    "provider_media_id": "snapshot-short-video-28",
    "type": "shortVideo",
    "account_name": "汽车有话说",
    "city": "全国",
    "province": "全国",
    "platform_name": "视频号",
    "industry": "汽车",
    "audience_gender": "不限",
    "fans": 20800,
    "price": 48
  },
  {
    "id": "snapshot-short-video-29",
    "provider_media_id": "snapshot-short-video-29",
    "type": "shortVideo",
    "account_name": "热度新闻传媒",
    "city": "全国",
    "province": "全国",
    "platform_name": "抖音",
    "industry": "生活/综合",
    "audience_gender": "不限",
    "fans": 12000,
    "price": 138
  },
  {
    "id": "snapshot-short-video-30",
    "provider_media_id": "snapshot-short-video-30",
    "type": "shortVideo",
    "account_name": "热度资讯",
    "city": "全国",
    "province": "全国",
    "platform_name": "抖音",
    "industry": "生活/综合",
    "audience_gender": "不限",
    "fans": 12000,
    "price": 138
  }
];
