<template>
  <div class="compute-page"><AuraPreviewBanner title="算力中心 · 演示快照" description="余额、趋势和流水均为固定本地示例，不代表真实账户，不会发生充值或扣费。" /><section class="balance"><div><span>演示算力余额</span><strong>{{ DEMO_CONFIG.aura.demoUser.balance.toLocaleString() }}<small>算力</small></strong><p>用于展示商品套图、服饰套图等能力的计费方式</p></div><button @click="requireFullEdition('算力充值', 'recharge')"><el-icon><Plus /></el-icon>充值算力</button></section><section class="card"><header><div><h2>算力消耗趋势</h2><p>固定演示快照</p></div><div class="range"><button v-for="days in [7,14]" :key="days" :class="{ active: rangeDays === days }" @click="rangeDays = days">近 {{ days }} 天</button></div></header><div ref="chartRef" class="chart"></div></section><section class="card"><header><div><h2>消费明细</h2><p>本地数据筛选与分页</p></div><div class="range"><button v-for="option in statusOptions" :key="option.value" :class="{ active: status === option.value }" @click="changeStatus(option.value)">{{ option.label }}</button></div></header><el-table :data="pageRows" stripe size="small"><el-table-column prop="createdAt" label="时间" min-width="140" /><el-table-column prop="modelName" label="模型" min-width="145" /><el-table-column prop="featureName" label="功能" min-width="110" /><el-table-column label="数量" width="90"><template #default="{ row }">{{ row.quantity }}{{ row.unit }}</template></el-table-column><el-table-column label="消耗算力" width="110" align="center"><template #default="{ row }"><span class="cost" :class="{ refund: row.status === 'refunded' }">{{ row.status === 'refunded' ? '+' : '-' }}{{ row.cost }}</span></template></el-table-column><el-table-column label="状态" width="100"><template #default="{ row }"><el-tag size="small" :type="row.status === 'refunded' ? 'info' : 'success'">{{ row.status === 'refunded' ? '已退款' : '成功' }}</el-tag></template></el-table-column></el-table><footer><span>共 {{ filteredRows.length }} 条演示记录</span><el-pagination small background layout="prev, pager, next" :total="filteredRows.length" :page-size="pageSize" :current-page="page" @current-change="page = $event" /></footer></section></div>
</template>
<script setup lang="ts" name="AuraCompute">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from "vue";
import * as echarts from "echarts";
import { DEMO_CONFIG } from "@/config/demo";
import AuraPreviewBanner from "../components/AuraPreviewBanner.vue";
import { consumeLogs, consumeTrend } from "../preview/fixtures";
import { useAuraPreviewGate } from "../preview/useAuraPreviewGate";
const { requireFullEdition } = useAuraPreviewGate(); const chartRef=ref<HTMLElement>(); const rangeDays=ref(14); let chart:echarts.ECharts|undefined;
const visibleTrend=computed(()=>consumeTrend.slice(-rangeDays.value)); const status=ref<"all"|"success"|"refunded">("all"); const statusOptions=[{label:"全部",value:"all" as const},{label:"成功",value:"success" as const},{label:"退款",value:"refunded" as const}]; const page=ref(1); const pageSize=6; const filteredRows=computed(()=>status.value==="all"?consumeLogs:consumeLogs.filter(row=>row.status===status.value)); const pageRows=computed(()=>filteredRows.value.slice((page.value-1)*pageSize,page.value*pageSize)); const changeStatus=(value:typeof status.value)=>{status.value=value;page.value=1;};
const render=()=>{if(!chartRef.value)return;chart ||= echarts.init(chartRef.value);chart.setOption({grid:{left:12,right:12,top:25,bottom:10,containLabel:true},tooltip:{trigger:"axis"},xAxis:{type:"category",data:visibleTrend.value.map(i=>i.date),axisLine:{show:false},axisTick:{show:false},axisLabel:{color:"#8a8fa3",fontSize:9}},yAxis:{type:"value",splitLine:{lineStyle:{color:"rgba(124,58,237,.08)"}},axisLabel:{color:"#8a8fa3",fontSize:9}},series:[{type:"bar",barMaxWidth:24,data:visibleTrend.value.map(i=>i.value),itemStyle:{borderRadius:[5,5,0,0],color:new echarts.graphic.LinearGradient(0,0,0,1,[{offset:0,color:"#8b5cf6"},{offset:1,color:"#c4b5fd"}])}}]});}; const resize=()=>chart?.resize(); watch(rangeDays,()=>nextTick(render)); onMounted(()=>{render();window.addEventListener("resize",resize)}); onBeforeUnmount(()=>{window.removeEventListener("resize",resize);chart?.dispose()});
</script>
<style lang="scss" scoped>
.compute-page{display:flex;min-height:100%;flex-direction:column;gap:14px}.balance{position:relative;overflow:hidden;display:flex;align-items:center;justify-content:space-between;padding:24px 28px;border-radius:20px;color:#fff;background:radial-gradient(circle at 85% 20%,rgba(244,114,182,.4),transparent 30%),linear-gradient(125deg,#312e81,#6d28d9 60%,#8b5cf6);box-shadow:0 16px 40px rgba(76,29,149,.2);span{font-size:11px;color:rgba(255,255,255,.75)}strong{display:block;margin:4px 0;font-size:34px;small{margin-left:7px;font-size:11px}}p{margin:0;color:rgba(255,255,255,.68);font-size:10px}button{display:inline-flex;align-items:center;gap:5px;padding:9px 15px;border:1px solid rgba(255,255,255,.28);border-radius:11px;color:#6d28d9;background:#fff;font-size:11px;font-weight:700;cursor:pointer}}.card{padding:18px;border:1px solid var(--ai-border);border-radius:var(--ai-radius);background:#fff;box-shadow:var(--ai-shadow);>header{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:12px;h2{margin:0;font-size:13px}p{margin:3px 0 0;color:var(--ai-muted);font-size:9px}}}.range{display:flex;gap:5px;button{padding:5px 9px;border:1px solid var(--ai-border);border-radius:8px;color:var(--ai-muted);background:#fff;font-size:9px;cursor:pointer;&.active{color:var(--ai-violet-deep);border-color:var(--ai-border-strong);background:var(--ai-tint)}}}.chart{height:260px}.cost{color:#ef4444;font-weight:700;&.refund{color:#10b981}}footer{display:flex;align-items:center;justify-content:space-between;margin-top:14px;color:var(--ai-muted);font-size:9px}@media(max-width:600px){.balance{align-items:flex-start;flex-direction:column;gap:18px;padding:21px}.card>header{align-items:flex-start;flex-direction:column}.card{padding:13px;overflow-x:auto}footer{align-items:flex-start;flex-direction:column;gap:10px}}
</style>
