<template>
  <el-dialog :model-value="modelValue" :title="item?.title || '案例详情'" width="min(980px, 94vw)" class="aura-case-dialog" destroy-on-close @update:model-value="emit('update:modelValue',$event)">
    <div v-if="item" class="detail">
      <aside><img :src="selectedImage || item.coverUrl" :alt="item.title" /><div class="thumbs"><button v-for="image in allImages" :key="image.id" :class="{on:selectedImage===image.url}" @click="selectedImage=image.url"><img :src="image.url" :alt="image.label" /></button></div></aside>
      <main><div class="meta"><span>{{ item.kind==='product'?'商品套图':'服饰套图' }}</span><span>{{ item.category }}</span><span>{{ item.modelName }}</span></div><h2>{{ item.title }}</h2><div class="stats"><span><el-icon><View /></el-icon>{{ item.views }}</span><span><el-icon><Star /></el-icon>{{ item.likes }}</span><span>{{ allImages.length }} 张成片</span></div><section v-if="item.sourceUrls.length"><h3>{{ item.kind==='product'?'商品原图':'服装与模特素材' }}</h3><div class="sources"><img v-for="url in item.sourceUrls" :key="url" :src="url" alt="案例原始素材" /></div></section><section><h3>创作内容</h3><button v-for="section in item.sections" :key="section.id" class="section-row" @click="selectedImage=section.images[0]?.url"><div><strong>{{ section.name }}</strong><p>{{ section.description }}</p></div><span>{{ section.images.length }} 张 · {{ section.ratio || '自适应' }}</span></button></section></main>
    </div>
    <template #footer><el-button @click="emit('update:modelValue',false)">继续浏览</el-button><el-button @click="requireFullEdition('下载整套素材','download')">下载全部</el-button><el-button type="primary" @click="requireFullEdition('一键做同款','useTemplate')">一键做同款</el-button></template>
  </el-dialog>
</template>
<script setup lang="ts">
import { computed, ref, watch } from "vue"; import type { AuraPreviewItem } from "../preview/types"; import { useAuraPreviewGate } from "../preview/useAuraPreviewGate";
const props=defineProps<{modelValue:boolean;item:AuraPreviewItem|null}>(); const emit=defineEmits<{(e:"update:modelValue",value:boolean):void}>(); const {requireFullEdition}=useAuraPreviewGate(); const selectedImage=ref(""); const allImages=computed(()=>props.item?.sections.flatMap(section=>section.images)||[]); watch(()=>props.item,item=>selectedImage.value=item?.coverUrl||"",{immediate:true});
</script>
<style lang="scss" scoped>
.detail{display:grid;grid-template-columns:minmax(0,1.2fr) minmax(300px,.8fr);gap:22px}.detail aside>img{display:block;width:100%;max-height:560px;border-radius:14px;object-fit:contain;background:#f5f3f8}.thumbs{display:flex;gap:7px;margin-top:9px;overflow-x:auto}.thumbs button{width:58px;height:58px;flex-shrink:0;padding:2px;border:2px solid transparent;border-radius:9px;background:#fff;cursor:pointer}.thumbs button.on{border-color:var(--ai-violet)}.thumbs img{width:100%;height:100%;border-radius:6px;object-fit:cover}.meta{display:flex;flex-wrap:wrap;gap:6px}.meta span{padding:4px 8px;border-radius:7px;color:var(--ai-violet-deep);background:var(--ai-tint);font-size:10px}.detail h2{margin:12px 0 8px;font-size:23px}.stats{display:flex;gap:14px;color:var(--ai-muted);font-size:11px}.stats span{display:flex;align-items:center;gap:4px}.detail section{margin-top:22px}.detail h3{margin:0 0 9px;font-size:13px}.sources{display:flex;gap:7px}.sources img{width:72px;height:72px;border-radius:10px;object-fit:cover}.section-row{display:flex;width:100%;align-items:center;justify-content:space-between;gap:12px;padding:11px 0;border:0;border-bottom:1px solid #f0edf5;text-align:left;background:none;cursor:pointer}.section-row strong{font-size:11px}.section-row p{margin:3px 0 0;color:var(--ai-muted);font-size:9px}.section-row>span{flex-shrink:0;color:var(--ai-muted);font-size:9px}@media(max-width:760px){.detail{grid-template-columns:1fr}}
</style>
